// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('App', ['baguaImageEditor']).controller("appCtrl", [
    '$scope', '$rootScope', function($scope, $rootScope) {
      var clean_bagua, current_img_editor;
      current_img_editor = null;
      $scope.img_src = null;
      $scope.img_percent = 0.5;
      $scope.img_aspect = null;
      $scope.img_url = 'sample.png';
      $scope["switch"] = function() {
        var idx, src_url, urls;
        urls = ['sample.png', 'sample_small.gif', 'sample_long.jpg', 'sample_larger.jpg'];
        idx = urls.indexOf($scope.img_url);
        urls.splice(idx, 1);
        src_url = urls[Math.floor(Math.random() * urls.length)];
        return $scope.img_url = src_url;
      };
      $scope.has_editor = function() {
        return Boolean(current_img_editor);
      };
      $scope.scale_capture = function() {
        $scope.scale();
        return $scope.capture();
      };
      $scope.scale = function() {
        if (!current_img_editor) {
          return;
        }
        return $scope.img_aspect = current_img_editor.scale($scope.img_percent);
      };
      $scope.capture = function() {
        var dataurl, media, new_media;
        if (!current_img_editor) {
          return;
        }
        dataurl = current_img_editor.capture();
        $scope.img_src = dataurl;
        media = {
          name: 'sample.jpg',
          lastModified: new Date(),
          lastModifiedDate: new Date()
        };
        new_media = current_img_editor.blob(media, dataurl);
        return console.log(new_media);
      };
      clean_bagua = $rootScope.$on('bagua.loaded', function(e, img_editor, reload) {
        current_img_editor = img_editor;
        $scope.img_aspect = img_editor.aspect();
        return $scope.$apply();
      });
      return $scope.$on('$destroy', function() {
        if (current_img_editor) {
          current_img_editor.destroy();
        }
        if (clean_bagua) {
          return clean_bagua();
        }
      });
    }
  ]);

}).call(this);
